# Generated by Django 4.0.6 on 2022-09-02 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
