# Generated by Django 4.0.6 on 2022-09-02 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0002_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('productname', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('carbrand', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='static/uploadedproducts')),
                ('image2', models.ImageField(upload_to='static/uploadedproducts')),
                ('image3', models.ImageField(upload_to='static/uploadedproducts')),
                ('image4', models.ImageField(upload_to='static/uploadedproducts')),
                ('catid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ga.categories')),
            ],
        ),
    ]
