# Generated by Django 4.0.6 on 2022-09-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0003_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='prodbrands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productbrand', models.CharField(default=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='prodbrand',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='prodid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_ga.prodbrands'),
            preserve_default=False,
        ),
    ]
