# Generated by Django 4.0.6 on 2022-09-15 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0008_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stocks',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
