# Generated by Django 4.0.6 on 2022-09-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0009_products_stock_status_products_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='retrn',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='retrn_policy',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
