# Generated by Django 4.0.6 on 2022-09-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0010_products_retrn_products_retrn_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
