# Generated by Django 4.0.6 on 2022-09-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0012_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
