# Generated by Django 4.0.6 on 2022-09-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0013_cart_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_number', models.CharField(max_length=16)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(null=True)),
                ('discount_percentage', models.IntegerField(null=True)),
                ('minimum_amount', models.IntegerField(default=500)),
            ],
        ),
    ]
