# Generated by Django 4.0.6 on 2022-09-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0015_coupon_expiry_date_coupon_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrands',
            name='carlogo',
            field=models.ImageField(default=True, upload_to='static/uploadedproducts'),
        ),
    ]
