# Generated by Django 4.0.6 on 2022-09-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0017_myusers_refferal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='refferal_code',
            field=models.CharField(max_length=50),
        ),
    ]
