# Generated by Django 4.0.6 on 2022-09-23 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0018_alter_myusers_refferal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dis_price',
            field=models.BigIntegerField(null=True),
        ),
    ]
