# Generated by Django 4.0.6 on 2022-09-23 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0019_products_dis_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='retrn_policy',
            field=models.CharField(default='10', max_length=100, null=True),
        ),
    ]
