# Generated by Django 4.0.6 on 2022-09-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0020_alter_products_retrn_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='retrn_policy',
            field=models.DateTimeField(null=True),
        ),
    ]
