# Generated by Django 4.0.6 on 2022-09-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0021_alter_products_retrn_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='applied_coupons',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
