# Generated by Django 4.0.6 on 2022-09-25 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0022_myusers_applied_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='retrn_policy',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
