# Generated by Django 4.0.6 on 2022-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0023_alter_products_retrn_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dis_applied',
            field=models.BooleanField(default=False),
        ),
    ]
