# Generated by Django 4.0.6 on 2022-09-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0025_monthly_sales_report_sales_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dis_proprice',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='total_disprice',
            field=models.BigIntegerField(null=True),
        ),
    ]
