# Generated by Django 4.0.6 on 2022-09-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0026_products_dis_proprice_products_total_disprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='dis_price_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
