# Generated by Django 4.0.6 on 2022-09-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0027_products_dis_price_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=True, upload_to='static/uploadedproducts')),
                ('image2', models.ImageField(default=True, upload_to='static/uploadedproducts')),
                ('image3', models.ImageField(default=True, upload_to='static/uploadedproducts')),
            ],
        ),
    ]
