# Generated by Django 4.0.6 on 2022-10-03 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0030_guest_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='recent_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ga.products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ga.myusers')),
            ],
        ),
    ]
