# Generated by Django 4.0.6 on 2022-10-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0032_salesreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to='static/uploadedproducts'),
        ),
    ]
