# Generated by Django 4.0.6 on 2022-10-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0033_categories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest_cart',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ga.myusers'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=models.ImageField(null=True, upload_to='static/catgoryicons'),
        ),
    ]
