# Generated by Django 4.0.6 on 2022-10-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0034_guest_cart_userid_alter_categories_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest_cart',
            name='total_price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
