# Generated by Django 4.0.6 on 2022-10-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0035_alter_guest_cart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest_cart',
            name='userid',
        ),
        migrations.AddField(
            model_name='guest_cart',
            name='user_session',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
