# Generated by Django 4.0.6 on 2022-10-12 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0036_remove_guest_cart_userid_guest_cart_user_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest_cart2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_session', models.CharField(max_length=20)),
                ('quantity', models.CharField(max_length=100)),
                ('total_price', models.CharField(max_length=100, null=True)),
                ('productid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_ga.products')),
            ],
        ),
    ]
