from django.urls import path
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login,name='login'),
    path('otplogin', views.otplogin,name='otplogin'),
    path('register', views.register,name='register'),
    path('logout', views.logout,name='logout'),
    path('superuser', views.adminlogin,name='adminlogin'),
    # path('adminhome', views.adminhome,name='adminhome'),
    path('adminlogout', views.adminlogout,name='adminlogout'),
    path('userdatas', views.userdatas,name='userdatas'),
    path('otpverify', views.otpverify,name='otpverify'),
    # path('otpfunc', views.otpfunc,name='otpfunc'),
    path('regotpverify/<context>', views.regotpverify,name='regotpverify'),
    path('addproduct', views.addproduct,name='addproduct'),
    path('addcategory', views.addcategory,name='addcategory'),
    path('deletecategory/<int:id>', views.deletecategory,name='deletecategory'),
    path('editcategory/<int:id>', views.editcategory,name='editcategory'),
    path('deletecarbr/<int:id>', views.deletecarbr,name='deletecarbr'),
    path('editcacarbr/<int:id>', views.editcarbr,name='editcarbr'),

    path('productlist', views.productlist,name='productlist'),
    path('sidebar', views.sidebar,name='sidebar'),
    path('productmanage', views.productmanage,name='productmanage'),
    path('brandman', views.brandman,name='brandman'),
    path('carbrandman', views.carbrandman,name='carbrandman'),
    path('userprofile', views.userprofile,name='userprofile'),
    
    path('addaddress', views.addaddress,name='addaddress'),
    path('editprofile', views.editprofile,name='editprofile'),
    path('addbanner', views.addbanner,name='addbanner'),

    path('cartlist', views.cartlist,name='cartlist'),
    path('wishlistt', views.wishlistt,name='wishlistt'),
    path('remove_wish/<int:id>', views.remove_wish,name='remove_wish'),
    path('adminDashboard', views.adminDashboard,name='adminDashboard'),
    path('products_main', views.products_main,name='products_main'),
    path('cart_update', views.cart_update,name='cart_update'),
    path('couponman', views.couponman,name='couponman'),
    path('delete_coupon/<int:id>', views.delete_coupon,name='delete_coupon'),
    path('shopbycar', views.shopbycar,name='shopbycar'),
    path('shopbycategory', views.shopbycategory,name='shopbycategory'),
    path('sales', views.sales_report_date,name='sales'),
    path('export_to_excel', views.export_to_excel,name='export_to_excel'),
    # path('export_to_excel1', views.export_to_excel1,name='export_to_excel1'),
    path('export_to_pdf', views.export_to_pdf,name='export_to_pdf'),
    
    path('search', views.search,name='search'),
    # path('export_to_pdf1', views.export_to_pdf1,name='export_to_pdf1'),
    # path('monthly_sales', views.monthly_sales,name='monthly_sales'),
    path('clear_all_offer/<int:id>', views.clear_all_offer, name='clear_all_offer'),
    path('clear_cate_offer/<int:id>', views.clear_cate_offer, name='clear_cate_offer'),
    path('clear_pro_offer/<int:id>', views.clear_pro_offer, name='clear_pro_offer'),
    path('sort/<int:id>', views.sort,name='sort'),
    path('filter/<int:id>', views.filter,name='filter'),
    path('filter/detail/<int:id>', views.prodetail,name='prodetail'),
    path('filterbycar/<str:id>', views.filterbycar,name='filterbycar'),
    path('qplus/<int:id>', views.qplus,name='qplus'),
    path('qminus/<int:id>', views.qminus,name='qminus'),
    path('remove_cart/<int:id>', views.remove_cart,name='remove_cart'),
    path('detail/<id>', views.prodetail,name='prodetail'),
    path('editproduct/<int:id>', views.editproduct,name='editproduct'),
    path('deleteproduct/<int:id>', views.deleteproduct,name='deleteproduct'),
    path('changepassword/<int:id>', views.changepassword,name='changepassword'),
    path('addoffer/<int:id>', views.addoffer,name='addoffer'),
    path('addoffers', views.addoffers,name='addoffers'),
    path('block/<int:id>', views.block,name='block'),
    

    path('add_cart_guest/<int:pid>',views.add_cart_guest, name='add_cart_guest'),
    path('gcart_remove/<int:id>',views.gcart_remove, name='gcart_remove'),
    path('gcart_view/', views.gcart_view, name="gcart_view"),
    path('gcart_update/', views.gcart_update, name="gcart_update"),
]
