# Generated by Django 4.0.6 on 2022-09-10 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ga', '0008_address'),
        ('order', '0002_address_remove_order_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ga.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
