# Generated by Django 4.0.6 on 2022-09-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_address_delete_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(default='Confirmed', max_length=50),
        ),
    ]
