# Generated by Django 4.0.6 on 2022-09-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_orderproduct_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
